In [1]:
import pandas as pd 
import numpy as np

In [2]:
text = {"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment ","Aiyug write comment"],"Output":[1,1,0,0] }

In [3]:
text =pd.DataFrame(text)

In [4]:
text 

text  Output
0     People watch Aiyug       1
1      Aiyug watch Aiyug       1
2  People write comment        0
3    Aiyug write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv =CountVectorizer(lowercase=True, stop_words='english', binary=True)

In [7]:
bow =cv.fit_transform(text['text'])

In [8]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [10]:
cv.transform(["hello comment  my name watch is anubhuti "]).toarray()

array([[0, 1, 0, 1, 0]])

In [11]:
!pip install scikit-learn


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


N game

In [12]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "I love natural language processing "
tokens =word_tokenize(text)
n = 3 

bigrams =list(ngrams(tokens, n)) 
print("bigrams:-",bigrams)  

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\chand/nltk_data'
    - 'c:\\Users\\chand\\AppData\\Local\\Programs\\Python\\Python311\\nltk_data'
    - 'c:\\Users\\chand\\AppData\\Local\\Programs\\Python\\Python311\\share\\nltk_data'
    - 'c:\\Users\\chand\\AppData\\Local\\Programs\\Python\\Python311\\lib\\nltk_data'
    - 'C:\\Users\\chand\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
