In [49]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


c:\Users\chand\AppData\Local\Programs\Python\Python312\python.exe: No module named pip


In [50]:
import numpy as np
print("successfully installed")

successfully installed


In [51]:
print("numpy version: ", np.__version__)

numpy version:  2.1.3


In [52]:
# Array and list  

# Array similar data store krta hai hain
# array >>>>>>>[1,2,3,4,5,6,7,8,9] 

# list >>>>>>[1,2,3,4,5,6,7,8,9, "ritik", 2.5, True, [1,2,3]]

list convert into array

In [53]:
lst = [1,2,3,4,5]
print("type of list:-",type(lst))
arr =np.array(lst)
print(arr)
print("type of array:-",type(arr))

type of list:- <class 'list'>
[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [54]:
arrr =np.array([1,2,3,4,5])

In [55]:
print(arrr)
print("type of array:-",type(arrr))

[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [56]:
lst = list(range(1, 20)) # list function is used to create list and range function is used to create range

In [57]:
type(lst)
arr =np.array(lst)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
arr =np.arange(1,20) #arange function is used to create array 
type(arr)

numpy.ndarray

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [60]:
arr =np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [61]:
arr =np.zeros((5,10))  # 5 rows and 10 columns and zero is used to create array
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
arr=np.ones((5,10)) # one is used to create array
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
np.linspace(1,10,5) # linspace function is used to create array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

1D array convert into 2D

In [64]:
arr=np.arange(0,30) # arange function is used to create array

In [65]:
arr.reshape(5,6) # reshape function 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [66]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [67]:
arr=np.random.randint(1,5,9) # random function is used to create array
arr

array([3, 1, 2, 1, 4, 3, 2, 2, 4], dtype=int32)

In [68]:
arr=np.random.randint(1,5,(5,2)) 
arr

array([[2, 1],
       [1, 4],
       [3, 1],
       [4, 2],
       [2, 2]], dtype=int32)

In [69]:
arr=np.random.random((5,10)) # seed function is used to create array
arr

array([[7.99436561e-01, 4.72594775e-01, 6.32873372e-04, 8.52745218e-01,
        3.53740379e-02, 3.39436988e-01, 1.92522617e-01, 9.87037835e-01,
        9.21058046e-01, 8.95692238e-01],
       [9.80723935e-01, 4.73824019e-01, 5.42166011e-01, 3.91117437e-01,
        1.15034797e-01, 5.87484019e-01, 7.85837223e-01, 9.77201363e-01,
        9.74501529e-01, 2.31177701e-02],
       [4.60029166e-01, 9.52598351e-01, 6.94298385e-01, 5.80122328e-01,
        9.91198838e-01, 4.49016257e-01, 5.12363681e-02, 6.11136268e-01,
        7.93417562e-01, 9.94652808e-01],
       [9.76206683e-01, 4.14012618e-01, 7.52487248e-01, 1.63080852e-01,
        5.84065125e-01, 5.69007585e-01, 8.29418465e-01, 5.06104289e-01,
        8.35650702e-01, 3.66232813e-01],
       [8.66016218e-01, 4.10989007e-01, 6.50556666e-01, 9.53643313e-01,
        8.38187032e-01, 2.90795727e-01, 6.81259965e-01, 4.11178122e-01,
        2.34172420e-01, 2.10776144e-01]])

In [70]:
print("array shape :-",arr.shape)
print("array size:-",arr.size)
print("array data type:-",arr.dtype)
print("array dimension:-",arr.ndim)

array shape :- (5, 10)
array size:- 50
array data type:- float64
array dimension:- 2


In [71]:
arr.flatten() #  2d array to 1d array

array([7.99436561e-01, 4.72594775e-01, 6.32873372e-04, 8.52745218e-01,
       3.53740379e-02, 3.39436988e-01, 1.92522617e-01, 9.87037835e-01,
       9.21058046e-01, 8.95692238e-01, 9.80723935e-01, 4.73824019e-01,
       5.42166011e-01, 3.91117437e-01, 1.15034797e-01, 5.87484019e-01,
       7.85837223e-01, 9.77201363e-01, 9.74501529e-01, 2.31177701e-02,
       4.60029166e-01, 9.52598351e-01, 6.94298385e-01, 5.80122328e-01,
       9.91198838e-01, 4.49016257e-01, 5.12363681e-02, 6.11136268e-01,
       7.93417562e-01, 9.94652808e-01, 9.76206683e-01, 4.14012618e-01,
       7.52487248e-01, 1.63080852e-01, 5.84065125e-01, 5.69007585e-01,
       8.29418465e-01, 5.06104289e-01, 8.35650702e-01, 3.66232813e-01,
       8.66016218e-01, 4.10989007e-01, 6.50556666e-01, 9.53643313e-01,
       8.38187032e-01, 2.90795727e-01, 6.81259965e-01, 4.11178122e-01,
       2.34172420e-01, 2.10776144e-01])

In [72]:
arr.ravel() 

array([7.99436561e-01, 4.72594775e-01, 6.32873372e-04, 8.52745218e-01,
       3.53740379e-02, 3.39436988e-01, 1.92522617e-01, 9.87037835e-01,
       9.21058046e-01, 8.95692238e-01, 9.80723935e-01, 4.73824019e-01,
       5.42166011e-01, 3.91117437e-01, 1.15034797e-01, 5.87484019e-01,
       7.85837223e-01, 9.77201363e-01, 9.74501529e-01, 2.31177701e-02,
       4.60029166e-01, 9.52598351e-01, 6.94298385e-01, 5.80122328e-01,
       9.91198838e-01, 4.49016257e-01, 5.12363681e-02, 6.11136268e-01,
       7.93417562e-01, 9.94652808e-01, 9.76206683e-01, 4.14012618e-01,
       7.52487248e-01, 1.63080852e-01, 5.84065125e-01, 5.69007585e-01,
       8.29418465e-01, 5.06104289e-01, 8.35650702e-01, 3.66232813e-01,
       8.66016218e-01, 4.10989007e-01, 6.50556666e-01, 9.53643313e-01,
       8.38187032e-01, 2.90795727e-01, 6.81259965e-01, 4.11178122e-01,
       2.34172420e-01, 2.10776144e-01])

In [73]:
arr.shape

(5, 10)

In [74]:
arr.T.shape

(10, 5)

In [75]:
# 1D 
arr =np.arange(30)
arr[0]

np.int64(0)

In [76]:
arr =np.arange(30)
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# 2 D 
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [78]:
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


np.int64(6)

In [79]:
arr[1,3:5]

array([8, 9])

In [80]:
arr[0:5,1:2]   # row (o:5 means 0 to 4), column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [81]:
arr[7:8,4][0]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [82]:
arr[11,4]

np.int64(59)

In [83]:
arr[-1,-1] # we start from down side aslo

np.int64(59)

In [84]:
#3d array
arr =np.array(np.arange(225).reshape(5,15,3))
arr.ndim, arr.shape, arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [85]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [86]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [87]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [88]:
arr[2][3][1]=200
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 200, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [89]:
arr =np.array([3,5,2,7,1])

In [90]:
arr.sort()
arr

array([1, 2, 3, 5, 7])

In [91]:
arr+2 # every element of array is + with 2

array([3, 4, 5, 7, 9])

In [92]:
arr*2 #every element * with 2 we can also do - , / ,etc opreation

array([ 2,  4,  6, 10, 14])

In [93]:
arr =np.array([3,2,1,5,4])
arr1 =np.array([3,2,1,5,4])
arr+arr1

array([ 6,  4,  2, 10,  8])