In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


c:\Users\chand\AppData\Local\Programs\Python\Python312\python.exe: No module named pip


In [1]:
import numpy as np
print("successfully installed")

successfully installed


In [2]:
print("numpy version: ", np.__version__)

numpy version:  2.1.3


In [ ]:
# Array and list  

# Array similar data store krta hai hain
# array >>>>>>>[1,2,3,4,5,6,7,8,9] 

# list >>>>>>[1,2,3,4,5,6,7,8,9, "ritik", 2.5, True, [1,2,3]]

list convert into array

In [3]:
lst = [1,2,3,4,5]
print("type of list:-",type(lst))
arr =np.array(lst)
print(arr)
print("type of array:-",type(arr))

type of list:- <class 'list'>
[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [4]:
arrr =np.array([1,2,3,4,5])

In [5]:
print(arrr)
print("type of array:-",type(arrr))

[1 2 3 4 5]
type of array:- <class 'numpy.ndarray'>


In [ ]:
st = list(range(1, 20)) # list function is used to create list and range function is used to create range

In [6]:
type(lst)
arr =np.array(lst)
arr 

array([1, 2, 3, 4, 5])

In [7]:
arr =np.arange(1,20) #arange function is used to create array 
type(arr)

numpy.ndarray

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
arr =np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
arr =np.zeros((5,10))  # 5 rows and 10 columns and zero is used to create array
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr=np.ones((5,10)) # one is used to create array
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(1,10,5) # linspace function is used to create array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

1D array convert into 2D

In [13]:
arr=np.arange(0,30) # arange function is used to create array

In [15]:
arr.reshape(5,6) # reshape function 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [17]:
arr=np.random.randint(1,5,9) # random function is used to create array
arr

array([2, 3, 2, 1, 2, 3, 4, 2, 2], dtype=int32)

In [18]:
arr=np.random.randint(1,5,(5,2)) 
arr

array([[4, 3],
       [2, 4],
       [2, 3],
       [2, 3],
       [3, 2]], dtype=int32)

In [19]:
arr=np.random.random((5,10)) # seed function is used to create array
arr

array([[0.09532877, 0.68434029, 0.05638312, 0.17317712, 0.83464899,
        0.99922529, 0.39982105, 0.68350008, 0.29775108, 0.06896253],
       [0.88716358, 0.64378737, 0.58714859, 0.84349884, 0.07720408,
        0.2140392 , 0.6689203 , 0.15086337, 0.15024878, 0.12792234],
       [0.67056913, 0.84681903, 0.78134026, 0.75296115, 0.44190467,
        0.51208866, 0.82416115, 0.12730449, 0.22112811, 0.75733767],
       [0.27410685, 0.8372785 , 0.79037381, 0.02308865, 0.98411527,
        0.99727671, 0.70810886, 0.10147803, 0.01472241, 0.58663454],
       [0.44188776, 0.34077426, 0.31176118, 0.89061639, 0.25487737,
        0.44456452, 0.95359298, 0.3166461 , 0.07744606, 0.95808147]])

In [20]:
print("array shape :-",arr.shape)
print("array size:-",arr.size)
print("array data type:-",arr.dtype)
print("array dimension:-",arr.ndim)

array shape :- (5, 10)
array size:- 50
array data type:- float64
array dimension:- 2


In [21]:
arr.flatten() #  2d array to 1d array

array([0.09532877, 0.68434029, 0.05638312, 0.17317712, 0.83464899,
       0.99922529, 0.39982105, 0.68350008, 0.29775108, 0.06896253,
       0.88716358, 0.64378737, 0.58714859, 0.84349884, 0.07720408,
       0.2140392 , 0.6689203 , 0.15086337, 0.15024878, 0.12792234,
       0.67056913, 0.84681903, 0.78134026, 0.75296115, 0.44190467,
       0.51208866, 0.82416115, 0.12730449, 0.22112811, 0.75733767,
       0.27410685, 0.8372785 , 0.79037381, 0.02308865, 0.98411527,
       0.99727671, 0.70810886, 0.10147803, 0.01472241, 0.58663454,
       0.44188776, 0.34077426, 0.31176118, 0.89061639, 0.25487737,
       0.44456452, 0.95359298, 0.3166461 , 0.07744606, 0.95808147])

In [22]:
arr.ravel() 

array([0.09532877, 0.68434029, 0.05638312, 0.17317712, 0.83464899,
       0.99922529, 0.39982105, 0.68350008, 0.29775108, 0.06896253,
       0.88716358, 0.64378737, 0.58714859, 0.84349884, 0.07720408,
       0.2140392 , 0.6689203 , 0.15086337, 0.15024878, 0.12792234,
       0.67056913, 0.84681903, 0.78134026, 0.75296115, 0.44190467,
       0.51208866, 0.82416115, 0.12730449, 0.22112811, 0.75733767,
       0.27410685, 0.8372785 , 0.79037381, 0.02308865, 0.98411527,
       0.99727671, 0.70810886, 0.10147803, 0.01472241, 0.58663454,
       0.44188776, 0.34077426, 0.31176118, 0.89061639, 0.25487737,
       0.44456452, 0.95359298, 0.3166461 , 0.07744606, 0.95808147])

In [23]:
arr.shape

(5, 10)

In [24]:
arr.T.shape

(10, 5)

In [25]:
# 1D 
arr =np.arange(30)
arr[0]

np.int64(0)

In [26]:
arr =np.arange(30)
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 2 D 
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [29]:
arr =np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


np.int64(6)

In [30]:
arr[1,3:5]

array([8, 9])

In [31]:
arr[0:5,1:2]   # row (o:5 means 0 to 4), column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [32]:
arr[7:8,4][0]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [33]:
arr[11,4]

np.int64(59)

In [34]:
arr[-1,-1] # we start from down side aslo

np.int64(59)

In [35]:
#3d array
arr =np.array(np.arange(225).reshape(5,15,3))
arr.ndim, arr.shape, arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [36]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [37]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [38]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [39]:
arr[2][3][1]=200
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 200, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [40]:
arr =np.array([3,5,2,7,1])

In [41]:
arr.sort()
arr

array([1, 2, 3, 5, 7])

In [42]:
arr+2 # every element of array is + with 2

array([3, 4, 5, 7, 9])

In [ ]:
arr*2 #every element * with 2 we can also do - , / ,etc opreation

array([ 2,  4,  6, 10, 14])

In [44]:
arr =np.array([3,2,1,5,4])
arr1 =np.array([3,2,1,5,4])
arr+arr1

array([ 6,  4,  2, 10,  8])