In [47]:
!pip install tensorflow


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [48]:
import tensorflow as tf 

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [50]:
import pandas as pd
import numpy as np

In [51]:
data = pd.read_csv("Credit.csv")

In [52]:
data

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4521 rows x 9 columns]

In [53]:
data['job'].unique()  

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown', nan], dtype=object)

In [54]:
job = {'admin.':0,'blue-collar':1,'entrepreneur':2,'housemaid':3,'management':4,'retired':5,'self-employed':6,'services':7,'student':8,'technician':9,'unemployed':10,'unknown':11}
data['job'] = data['job'].map(job)
data['marital'] = data['marital'].map({'married':0,'single':1,'divorced':2})
data['education'] = data['education'].map({'primary':0,'secondary':1,'tertiary':2})
data['housing'] = data['housing'].map({'yes':0,'no':1})
data['approval'] = data['approval'].map({'yes':0,'no':1})

In [55]:
data.drop_duplicates(inplace=True)

In [56]:
data.dropna(inplace=True)

In [57]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [58]:
x =data.drop('approval',axis=1)
y = data['approval']

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [60]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3452, 8), (863, 8), (3452,), (863,))

In [61]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [62]:
input_dim=8

In [64]:
model =Sequential()
# input layer
model.add(Dense(units=128,activation='relu',input_dim=input_dim))
# Dropout layer 
model.add(Dropout(0.2))
# Hidden layer

model.add(Dense(units = 64,activation='relu'))
model.add(Dense(units = 32,activation='relu'))
model.add(Dense(units = 16,activation='relu'))
model.add(Dense(units = 8,activation='relu'))
# output layer


model.add(Dense(units=1,activation='sigmoid'))


model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy','mae','mse'])

c:\Users\chand\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [65]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7960 - loss: 5.5059 - mae: 0.2854 - mse: 0.2055
Epoch 2/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8891 - loss: 0.6289 - mae: 0.3399 - mse: 0.1637
Epoch 3/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8638 - loss: 0.6478 - mae: 0.3880 - mse: 0.1822
Epoch 4/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8867 - loss: 0.4766 - mae: 0.3130 - mse: 0.1394
Epoch 5/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8774 - loss: 0.4567 - mae: 0.2964 - mse: 0.1329
Epoch 6/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8843 - loss: 0.4346 - mae: 0.2623 - mse: 0.1171
Epoch 7/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8803 - loss: 0.4067 - mae: 0.2675 - mse: 0.1192
Epoch 8/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8850 - loss: 0.3879 - mae: 0.2457 - mse: 0.1092
Epoch 9/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8839 - loss: 0.3721 - 

In [66]:
pred = model.predict(x_test)

27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step


In [67]:
import numpy

In [68]:
pred =numpy.ravel(pred)

In [69]:
pred

array([0.80860615, 0.83965725, 0.9017959 , 0.67318475, 0.67318475,
       0.79527855, 0.7619499 , 0.8489054 , 0.8375008 , 0.8711695 ,
       0.67318475, 0.776953  , 0.67318475, 0.7824079 , 0.98849416,
       0.80309886, 0.89642346, 0.7850213 , 0.8583567 , 0.91716564,
       0.7643968 , 0.98792356, 0.865718  , 0.90373915, 0.9666167 ,
       0.9755712 , 0.9175763 , 0.99287146, 0.7635948 , 0.7535355 ,
       0.8056066 , 0.9889071 , 0.77490485, 0.98999   , 0.8561392 ,
       0.9927419 , 0.67318475, 0.99090666, 0.9633946 , 0.8942562 ,
       0.73048353, 0.67318475, 0.7578789 , 0.978531  , 0.87216854,
       0.81077385, 0.9697214 , 0.99154586, 0.82132363, 0.85895276,
       0.99764276, 0.9933287 , 0.76083297, 0.9057885 , 0.69122386,
       0.8289347 , 0.9415773 , 0.85570496, 0.7660166 , 0.67318475,
       0.89061415, 0.8093451 , 0.67318475, 0.86024475, 0.9076064 ,
       0.89791447, 0.91299444, 0.9782177 , 0.7755118 , 0.8463124 ,
       0.99998504, 0.9468456 , 0.75218517, 0.71672565, 0.94887

In [70]:
y_test

3689    1
2174    1
2295    1
2321    0
934     1
       ..
197     1
2527    1
2305    1
3248    0
593     1
Name: approval, Length: 863, dtype: int64

In [71]:
output =pd.DataFrame({'actual':y_test,'prediction':(pred>=0.5).astype(int)})

In [72]:
output['prediction'].unique()

array([1])

In [73]:
output['actual'].unique()

array([1, 0])